### ISSUE TITLE
expose / add env info and version info to ag-bie site

### ISSUE THREAD

**Issue by mbohun** [ess-acppo/ag-bie#13]
- [ ] add env info (DEV, UAT, SIT, etc.) to the ag-bie site (for example to the footer)
- [ ] add/expose version numbers to the ag-bie site (version-s of war, jar files, /ws REST API version, etc.)

**Comment by mbohun** [comment]
NOTE: this is related/overlapping with issue: #15

**Comment by moziauddin** [comment]
these details are already available to the admin users. There is no reason for a business user to see this information.
