### ISSUE TITLE
add IP filtering / whitelist support to ag-bie (tmp solution before adding cas)

### ISSUE THREAD

**Issue by mbohun** [ess-acppo/ag-bie#14]
- [IP filter/whitelist linux/iptables based](https://gist.github.com/mbohun/4384953)
- [IP filter/whitelist grails spring security based](https://gist.github.com/mbohun/17fa070705be30962a4dd4a641dfc4be) this would be ideally integrated with userdetails DB
  - similar / on-related-note we should add email host white-list to
    - `/cas`
    - `/userdetails/registration/createAccount`

**Comment by moziauddin1** [comment]
IP filtering has been implemented using amazon aws infrastructure.
