### ISSUE TITLE
Add date of last index creation to home page

### ISSUE THREAD

**Issue by ess-acppo-djd** [ess-acppo/ag-bie#15]
Somewhere on the homepage provide the date and time the index was last processed.
This should be the date and time the "tlog" file is created in the directory /data/solr/bie/data/tlog.

Note that processing alternates between the directory 
> /data/solr/bie/data 

and the directory
> /data/solr/bie/data-offline

**Comment by mbohun** [comment]
**NOTE:** this is related/overlapping with issue: #13

**Comment by mbohun** [comment]
The first/simple implementation:
1. as user tomcat ():
    ```BASH
    echo \
       '<Context path="/version/" docBase="/var/lib/tomcat7/webapps-sit-ag-bie.oztaxa.com/version/" />' \
       > /var/lib/tomcat7/conf/Catalina/sit-ag-bie.oztaxa.com/version.xml
    ```
2.

**Comment by mbohun** [comment]
Although it is possible to read/report the time from `/data/solr/bie/data/tlog`/`/data/solr/bie/data-offline/tlog` you will need some mechanism to find out which one is the most "recent one":
```
ubuntu@ip-172-31-16-30:~$ ls -lahF /data/solr/bie/data-offline/tlog/
total 3.8M
drwxr-xr-x 2 tomcat7 tomcat7 4.0K Aug 22 00:20 ./
drwxr-xr-x 4 tomcat7 tomcat7 4.0K Jul 25 11:18 ../
-rw-r--r-- 1 tomcat7 tomcat7 3.8M Aug 22 00:20 tlog.0000000000000000188
```
```
ubuntu@ip-172-31-16-30:~$ ls -lahF /data/solr/bie/data/tlog/
total 1.4M
drwxr-xr-x 2 tomcat7 tomcat7 4.0K Aug 21 00:21 ./
drwxr-xr-x 4 tomcat7 tomcat7 4.0K Jul 25 11:18 ../
-rw-r--r-- 1 tomcat7 tomcat7 1.4M Aug 21 00:21 tlog.0000000000000000172
```
- one could either

**Comment by moziauddin** [comment]
This is not needed based on the business requirements at this stage
