### ISSUE TITLE
REST API / search page .searchResults.totalRecords question

### ISSUE THREAD

**Issue by mbohun** [ess-acppo/ag-bie#21]
- the number (`'.searchResults.totalRecords'`) differs **significantly**:
  ```
  curl -s 'https://sit-ag-bie.oztaxa.com/ws/search.json?q=*' \
      | jq '.searchResults.totalRecords'
  38743
  ```
  ```
  curl -s 'https://dev1-ag-bie.oztaxa.com/ws/search.json?q=*' \
      | jq '.searchResults.totalRecords'
  39419
  ```

The first OBVIOUS difference between these 2 environments is that while the older SIT env is daily rebuilding the SOLR data from **one single source** only: NAQS (tblBiota.csv); DEV1 is rebuilding the SOLR data from **two sources**: 
1. NAQS, and
2. [BNTi icn](https://dev56-icn.oztaxa.com/nxl/services/export/index) (displayed as: "NAQS NSL" in the search results)

example (https://dev1-ag-bie.oztaxa.com/species/tree/40017681/40017686#names):
![screenshot from 2018-08-31 17-13-31](https://user-images.githubusercontent.com/1772897/44898159-6bed6680-ad41-11e8-92d3-05c216336b56.png)

**Comment by moziauddin** [comment]
This is addressed in later release v0.6
