### ISSUE TITLE
GENERATE/OUTPUT and SAVE/PRESERVE build dependencies

### ISSUE THREAD

**Issue by mbohun** [ess-acppo/ag-bie#25]
1. **GENERATE / OUTPUT:**
   - grails:
     ```
     grails dependency-report
     ```
   - gradlew:
     ```BASH
     ./gradlew dependencies
     ```
   - maven:
     ```BASH
     mvn dependency:tree
     ```
2. **SAVE / PRESERVE:**
   - bundle the dependencies log file (together with git tag-s, SHA-s, etc.) into the artifact (`.jar`, `.war`, `.zip`)
   - backup jenkins build logs
   - gist (commit/upload the dependencies and build log-s, and other stats to a gist)

#### NOTES:
- When tracing, where some BUG / PROBLEM was introduced having a simple, easily/fast available list of dependencies makes the tracing faster / user-friendlier or at least less tedious
- THIS is one of the reasons you do **NOT** want to be deleting "old" build logs
- THIS issue is related to issue #8 (where the dependencies output is searched/checked-for `-SNAPSHOT` in order to stop a (release) build, to prevent/guard-against creating releases that would depend on `-SNAPSHOT` (unstable) components

**Comment by moziauddin** [comment]
No longer required.
