### ISSUE TITLE
REST API / search returning triple results?

### ISSUE THREAD

**Issue by mbohun** [ess-acppo/ag-bie#26]
#### triple results?
- https://dev1-ag-bie.oztaxa.com/species/tree/40031969/40023442#classification
![screenshot from 2018-10-17 16-57-29](https://user-images.githubusercontent.com/1772897/47065371-78187f00-d22e-11e8-9a82-07742b2481c7.png)

**Comment by moziauddin** [comment]
This bug is resolved in [v0.6](https://github.com/ess-acppo/ag-bie/releases/tag/v0.6).
