### ISSUE TITLE
Solr is populated with null values starting NAQS dump from Dec 14

### ISSUE THREAD

**Issue by ESS-ACPPO1** [ess-acppo/ag-bie#28]
The database has 5000 entries in total and search shows null for all 5000 entries

**Comment by mbohun** [comment]
I have seen this happening once before (apx. 3 months ago - in September) in the old (well first) UAT ag-bie env we setup back in May/June. That UAT env had the NAQS tblBiota.csv data loaded/processed/combined only once (on the 17th of May-or-June), and the NAQS tblBiota.csv were **NOT** running on that env daily; Later in September I wanted to use that UAT ag-bie env as it was "only to load more recent data into it" and that is when I ended up with that 5000 entries, with most of the data/fields set to null.

**Comment by moziauddin** [comment]
This was a one off and we could not recreate the issue any more.
