### ISSUE TITLE
Reporting Issues

### ISSUE THREAD

**Issue by charvolant** [ess-acppo/ag-bie#3]
Issues for ag-bie reporting. These may be addressed in other components but this is a good place to park things.

- [x] Raw input count
- [x] Count of discarded taxa for whatever reason. (This should not be happening)
- [x] Turn count.load.VIRUS and friends into count.load.nametype.VIRUS to make it clear this isn't coming from the kingdom.
- [x] Turn count.resolve.taxonConcept should be taxon concept instances to taxon concepts
- [x] Include code, rank, dataset, taxonomic status in report
- [ ] When choosing first in collisions, the chosen taxon should appear in the taxonID column
- [x] *.collision.match should be more clear about it just choosing the first (collision.warn)
- [ ] Include a log of names that have been simply, incontestably allocated.
- [x] Scientific name authorship, ensure it's in the report
- [ ] Subfamily mapped onto family
- [ ] "Removing placeholder ..." is a bad message since it only get removed at the end. Include action.

**Comment by ess-acppo-djd** [comment]
Note:
> Include a log of names that have been simply, incontestably allocated.
Don't log each name in the report, just include a count.

**Comment by ess-acppo-djd** [comment]
Specifically regarding the NAQS BioLink taxon input (tblBiota)

Names defined in the input as Literature Names (bitLiteratureName = 1) or Available Names (bitAvailableName = 1) are to be treated as synonyms of their parent record.

As synonyms of their parent, they should be treated as having a principal taxon which is their parent record, which is the accepted name for which they are a synonym.

Currently, these records trigger a diagnostic of 
```
dcterms:type=NOTE 
dcterms:subject=taxonResolver.noPrincipals
dcterms:description="Taxon TC[taxon concept details] has no principals, using all instances"
```
It is preferable this be suppressed for any name explicitly identified as a synonym.

**Comment by charvolant** [comment]
Stuff done so far.

* Raw input count
  * Appears as count.load.instance
* Count of discarded taxa for whatever reason. (This should not be happening)
  * Appears as count.load.forbidden
* Turn count.load.VIRUS and friends into count.load.nametype.VIRUS to make it clear this isn't coming from the kingdom.
  * Turned into count.load.name.VIRUS
* Turn count.resolve.taxonConcept should be taxon concept instances to taxon concepts
  * count.resolve.taxonConceptInstance counts the number of taxon concept instances that have been resolved. count.resolve.taxonConcept is the number of taxon concepts that have been resolved.
* Include code, rank, dataset, taxonomic status in report
  * Added
When choosing first in collisions, the chosen taxon should appear in the taxonID column
  * Done
* *.collision.match should be more clear about it just choosing the first (collision.warn)
  * Done and reamed to collision.warn
* Scientific name authorship, ensure it's in the report
 * Fixed

**Comment by moziauddin** [comment]
Reporting issues are now resolved.
