### ISSUE TITLE
Use of 'taxxas' as a label in ag-BIE

### ISSUE THREAD

**Issue by ess-acppo-djd** [ess-acppo/ag-bie#4]
cosmetic issue

1. 'taxxas' is a misspelling of 'TaxaaS'
TaxaaS is the system name for the entire Taxonomy as a Service component, which (when built) will comprise four instances of the BNTi editor and website, and the ag-BIE search and web services.

2. The use of 'taxxas' as a label in the folder structure of the ag-bie server is misleading, as these folders are those used for processing the BioLink Taxon Explorer data (also known as the NAQS taxa tree data).

All of the uses of 'taxxas' should be examined and an appropriate replacement label substituted.
All playbooks for ag-BIE to be updated.

This task should only be commenced when no other work is scheduled.

**Comment by moziauddin** [comment]
Not relevant any more. The folder structure is fine as is.
