### ISSUE TITLE
Data management

### ISSUE THREAD

**Issue by ess-acppo-djd** [ess-acppo/ag-bie#5]
A records management strategy (backup/archive/disposal) is required to deal with the various inputs and outputs to/from ag-BIE.

(This issue is a work in progress. This comment will be removed when it is deemed to be fully documented)

###### Known inputs:
- NAQS data files stored in /home/dawr
These files are pushed to the server by an automated process managed by ISD Import Systems.
They accumulate indefinitely with no automated archiving or disposal.
Four files are provided each day.
  - tblBiota_yyyymmdd.csv
  - tblBiotaAssociate_yyyymmdd.csv
  - tblBiotaCount_yyyymmdd.csv
  - tblCommonName_yyyymmdd.csv
Only tblBiota and tblCommonName are used by ag-BIE.

**Comment by moziauddin** [comment]
These files are now backing up to S3 bucket.
